"""
Standalone Reviewer test — Phase 3, step 1.

Does NOT call the council. Uses four fixed, hand-written dummy responses,
so a failure here can only mean one thing: the Reviewer prompt/model
combination doesn't hold its own contract (valid JSON, scores summing to
1.0) — not that today's council output happened to be reviewable or not.

Get this clean across a few consecutive runs BEFORE wiring anonymize()
into live Phase 2 output. A malformed review breaks the round, not just
degrades it.

Usage:
    python test_reviewer.py            # 1 run
    python test_reviewer.py --runs 5   # check consistency across runs
"""
import argparse
import asyncio

from core.models import Role
from core.ollama_client import call_role
from core.prompt_loader import get_system_prompt
from core.review import (
    build_review_prompt, extract_json, validate_review, normalize_scores,
    flag_quality_issues, ReviewParseError,
)

# Fixed on purpose — not pulled from a live council run. These are written
# to plausibly resemble Virgo/Pisces/Critic/Seer register without being
# generated by them, so a Reviewer failure isn't confounded by council
# output quality on a given day.
DUMMY_QUERY = (
    "Should I switch our session store from Redis to Postgres now that "
    "we're already running Postgres for everything else?"
)

DUMMY_RESPONSES = {
    "A": "Keep Redis for session storage. The access pattern is high-frequency, "
         "low-latency key lookups with TTL expiry — Postgres can do it, but you'd "
         "be reimplementing what Redis gives you for free, and adding write load "
         "to a database that's probably already your bottleneck under scale.",
    "B": "Consolidating onto Postgres removes an entire piece of infrastructure "
         "you have to operate, monitor, and pay for. One fewer system to reason "
         "about during an incident is worth some latency you likely won't notice "
         "unless you're already operating at a scale where this isn't your real question.",
    "C": "The question assumes sessions need a database at all. Depending on your "
         "auth model, signed stateless tokens might remove the need for server-side "
         "session storage entirely — worth checking before optimizing which store to use.",
    "D": "What's a session, and why does it need to live somewhere specific? I don't "
         "know what Redis or Postgres are for in this context, or why this choice "
         "matters enough to ask about.",
}

_SEP = "=" * 64


async def run_once(run_number: int) -> tuple[bool, bool]:
    """Returns (structurally_valid, no_quality_flags)."""
    print(f"\n{_SEP}\nRUN {run_number}\n{_SEP}")

    system_prompt = get_system_prompt("reviewer")
    user_prompt = build_review_prompt(
        query=DUMMY_QUERY,
        classification="unclassified",  # Phase 5 router doesn't exist yet
        content_by_letter=DUMMY_RESPONSES,
    )

    response = await call_role(Role.REVIEWER, system_prompt, user_prompt)

    if not response.ok:
        print(f"✗ Call failed: {response.error}")
        return False, False

    print(f"✓ Response received ({response.duration_ms}ms)")
    print(f"\nRaw output:\n{response.content}\n")

    try:
        parsed, was_repaired = extract_json(response.content)
        if was_repaired:
            print("  ⚠ JSON was malformed — recovered via repair_json")
    except ReviewParseError as e:
        print(f"✗ JSON extraction failed: {e}")
        return False, False

    problems = validate_review(parsed)
    if problems:
        print("✗ Validation failed:")
        for p in problems:
            print(f"  - {p}")
        return False, False

    print("✓ Valid review:")
    print(f"  Strongest: {parsed['strongest']} — {parsed['strongest_reason']}")
    print(f"  Blind spot: {parsed['weakest_blind_spot']} — {parsed['blind_spot_detail']}")
    print(f"  Collective miss: {parsed['collective_miss']}")
    raw_scores = {l: float(parsed["usefulness_scores"][l]) for l in ("A", "B", "C", "D")}
    print(f"  Raw scores: {raw_scores}")
    print(f"  Normalized: {normalize_scores(raw_scores)}")

    quality_flags = flag_quality_issues(parsed)
    for flag in quality_flags:
        print(f"  ⚠ {flag}")

    return True, len(quality_flags) == 0


async def main() -> None:
    parser = argparse.ArgumentParser(description="Standalone Reviewer contract test")
    parser.add_argument("--runs", type=int, default=1, help="Number of consecutive runs")
    args = parser.parse_args()

    results = [await run_once(i) for i in range(1, args.runs + 1)]

    print(f"\n{_SEP}")
    valid_count = sum(1 for valid, _ in results if valid)
    clean_count = sum(1 for valid, clean in results if valid and clean)
    print(f"{valid_count}/{len(results)} runs structurally valid")
    print(f"{clean_count}/{len(results)} runs valid AND free of content-quality flags")
    print(_SEP)


if __name__ == "__main__":
    asyncio.run(main())
